### ISSUE TITLE
Boombox softlock

### ISSUE THREAD

**Issue by Kondakov02** [SylviBlossom/LC-BoomboxYT#4]
When [Remnants mod](https://thunderstore.io/c/lethal-company/p/KawaiiBone/Remnants/) is loaded alongside this, picking up remnant boombox causes player to be softlocked. The inventory is inaccessible and player can't interact with anything.
Here's the stack trace and I also attached a full log file.
[WithBoomboxYT.log](https://github.com/SylviBlossom/BoomboxYT/files/14538400/WithBoomboxYT.log)

>[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BoomboxYT.Patches.SetControlTipsForItem (GrabbableObject __instance) (at <86d03fd8200b4cc5a3451e92511085ae>:IL_0017)
(wrapper dynamic-method) GrabbableObject.DMD<GrabbableObject::SetControlTipsForItem>(GrabbableObject)
(wrapper dynamic-method) GrabbableObject.DMD<GrabbableObject::EquipItem>(GrabbableObject)
GameNetcodeStuff.PlayerControllerB.SwitchToItemSlot (System.Int32 slot, GrabbableObject fillSlotWithItem) (at <af9b1eec498a45aebd42601d6ab85015>:IL_014C)
GameNetcodeStuff.PlayerControllerB.GrabObjectClientRpc (System.Boolean grabValidated, Unity.Netcode.NetworkObjectReference grabbedObject) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0130)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_2552479808 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0064)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:GrabObjectClientRpc(Boolean, NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:GrabObjectServerRpc(NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:__rpc_handler_1554282707(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:GrabObjectServerRpc(NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:BeginGrabObject()
GameNetcodeStuff.PlayerControllerB:Interact_performed(CallbackContext)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

>[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BoomboxYT.Patches.SetControlTipsForItem (GrabbableObject __instance) (at <86d03fd8200b4cc5a3451e92511085ae>:IL_0017)
(wrapper dynamic-method) GrabbableObject.DMD<GrabbableObject::SetControlTipsForItem>(GrabbableObject)
(wrapper dynamic-method) GrabbableObject.DMD<GrabbableObject::EquipItem>(GrabbableObject)
GameNetcodeStuff.PlayerControllerB.SwitchToItemSlot (System.Int32 slot, GrabbableObject fillSlotWithItem) (at <af9b1eec498a45aebd42601d6ab85015>:IL_014C)
GameNetcodeStuff.PlayerControllerB.GrabObjectClientRpc (System.Boolean grabValidated, Unity.Netcode.NetworkObjectReference grabbedObject) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0130)
GameNetcodeStuff.PlayerControllerB.GrabObjectServerRpc (Unity.Netcode.NetworkObjectReference grabbedObject) (at <af9b1eec498a45aebd42601d6ab85015>:IL_018C)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_1554282707 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0096)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:GrabObjectServerRpc(NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:BeginGrabObject()
GameNetcodeStuff.PlayerControllerB:Interact_performed(CallbackContext)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

**Comment by SylviBlossom** [comment]
sorry about that! the issue should be fixed in the latest update
